### ISSUE TITLE
add a back button to search for institutions after PlaidLink launches in institution mode/update

### ISSUE THREAD

**Issue by amykyta** [plaid/link#108]
We have two use cases where this would help.
- we want to preselect an institution but then allow a customer to select a different bank
- a customer changes banks and instead of updating their connection needs to establish a new one altogether.

**Comment by pbernasconi** [comment]
Thanks for raising this issue @amykyta. Link purposefully doesn't show the back button in the credentials view, due to the fact that most integrations that open Link using custom initializers do so with the objective of building a custom Institution select view.

If you'd like to show the institution select view, you'll have to iniatialize Link in the standard mode. The alternative would be to build logic inside of your Link integration where the `onExit` handler would open the view after a user exits the Link flow. We'll keep your ideas in mind however in the future!
