### ISSUE TITLE
Asynchronous work on success

### ISSUE THREAD

**Issue by mickeyreiss** [plaid/link#151]
What is the recommended integration technique for performing asynchronous work in `linkViewController(_: didSucceedWithPublicToken:, metadata:)` before dismissing the Plaid Link interface?

In my case, I'd like to upload the public token before dismissing the `PLKPlaidLinkViewController`. The issue is that the Plaid Link interface is still user interactive and does not indicate that progress to the user.

Here's my suggested solution:

Add an asynchronous success signature to the delegate protocol (see [`PKPaymentViewControllerDelegate`](https://developer.apple.com/reference/passkit/pkpaymentauthorizationviewcontrollerdelegate/1616195-paymentauthorizationviewcontroll) or for an example of this pattern). For backwards compatibility, this method could be optional and be called only if implemented.

I suspect there are a number of other solutions that could work as well.

Thanks!

**Comment by michaelckelly** [comment]
@mickeyreiss - Thanks for the question, we'll try to get you an answer as soon as we can!

**Comment by afh** [comment]
@mickeyreiss - Thank you for the suggestion! Providing some means of showing progress while the `PLKPlaidLinkViewDelegate` is doing async work within `linkViewController: didSucceedWithPublicToken:metadata:` would make for a useful addition to LinkKit and we'll take it into consideration for future improvements.

For now it is up to the `PLKPlaidLinkViewDelegate` to handle multiple calls to `linkViewController: didSucceedWithPublicToken:metadata:` from LinkKit due to user interaction while async work is being done.

**Comment by afh** [comment]
Hi @mickeyreiss wanted to follow up with a suggestion on how async work in `linkViewController: didSucceedWithPublicToken:metadata:` can be handled, have a look at: https://github.com/plaid/link/issues/185#issuecomment-322835908
