### ISSUE TITLE
onExit is not called with a mobile Link window is closed

### ISSUE THREAD

**Issue by dictions** [plaid/link#182]
|       Name       | Value |
|------------------|-------|
| Link `env`       |    sandbox   |
| Browser          |   chrome 59 (w/ mobile simulation)     |
| Operating system |   OSX 10.12.5    |

### A detailed description of the steps to reproduce the issue

1. Open plaid link (opens new tab)
2. Close the tab
3. `onExit` is not called

### What you expected to see?

I expect `onExit` to be called both when I click the "X" and when I close the tab. 

### What you saw instead?

`onExit` was not called when I closed the mobile link tab.

### Additional Info

In addition to this, I'm also receiving an error when I call `exit` on a link that has already been closed. Currently, there is no public API for determining `isOpen`. In the source, I see there is a private variable being created that has an `isOpen` method. Could this be exposed safely?

**Comment by michaelckelly** [comment]
Thanks for opening this @dictions - we're investigating this and will follow up with more info shortly!

**Comment by yawnr** [comment]
`onExit` is also not called when forcing Plaid to open in an iframe on mobile.

**Comment by pbernasconi** [comment]
Hey @dictions – The Link team has been hard at work to make the mobile experience on mobile as good, if not better, than Desktop, and have pushed an update to Link to **default to the `forceIframe` experience on mobile**.

Link will now consistently open inside of the same window page, and no longer open into a new browser by default. This should solve the issue where closing Link in a new tab does not call the `onExit` callback – since the mobile-tab window is no longer the mobile default experience!
