### ISSUE TITLE
1.1.0 zip file needs to be added to release on Github

### ISSUE THREAD

**Issue by idris** [plaid/link#208]
@afh could you please upload a `LinkKit.framework.zip` for the 1.1.0 release?  The Carthage json file lists it, but it's a 404: https://raw.githubusercontent.com/plaid/link/master/LinkKit.json

**Comment by afh** [comment]
Hello @idris, thanks for reaching out. The `LinkKit.framework.zip` for the 1.1.0 release has been available since the public release, yet there was a spurious `1.1.0` tag in the repo (LinkKit releases are tagged with the `ios/` prefix), which may have been confusing for Carthage. I've deleted the incorrect `1.1.0` tag.

```
% curl -sL $(curl -Ls https://raw.githubusercontent.com/plaid/link/master/LinkKit.json | grep 1.1.0 | cut -d\" -f4) | openssl dgst -sha256
0b48644f9528c557aa6355d14a3b37fa397f0b5773537ff33e01ef20476daf05

% cat Cartfile
binary "https://raw.githubusercontent.com/plaid/link/master/LinkKit.json"

% carthage update 
*** Downloading binary-only framework LinkKit at "https://raw.githubusercontent.com/plaid/link/master/LinkKit.json"
*** Downloading LinkKit.framework binary at "1.1.0"
```
