### ISSUE TITLE
Xan not Select account in IOS message extension Apps

### ISSUE THREAD

**Issue by hsmith825** [plaid/link#219]
When submitting an issue for [**Plaid Link iOS**](https://github.com/plaid/link/tree/master/ios)
please include the following information:

| Name              | Value              |
| ----------------- | ------------------ |
| Link `apiVersion` | PLKAPIv2                   |
| Link `env`        | production                   |
| LinkKit version   |       1.1.0             |
| iOS version       |  11.2.1                  |
| iOS device        |     IOS               |

### A detailed description of the steps to reproduce the issue
linkConfiguration = PLKConfiguration(key: "***************", env: .production, product: .auth, selectAccount: true, longtailAuth: false, apiVersion: .PLKAPIv2)

* Very, very difficult to select which account you are linking to once you have logged in.  Everything else works as expected
![screen shot 2017-12-18 at 2 42 57 pm](https://user-images.githubusercontent.com/1394060/34136597-94c19922-e41b-11e7-8111-874385d13e4b.png)

I discovered that if I click on the checks shown in the screenshots about 50% it will select the account.  I know how to get it to work.  I am certain most of my customers will give up.  Can anything be done.

Thanks!
Howard

* 
* 

### What you expected to see?
A view that is easy to select which of my accounts to use.  The one shown has one account and it is difficult to select that account/
### A screenshot that shows the state of the UI (if applicable)

**Comment by afh** [comment]
Hello @hsmith825,
thank you for reaching out. We are looking into it. To better understand the issue you are observing would you mind taking a moment to answer the following questions:

- In the screenshot you provided the account balance was visible but you edited the image for privacy, correct?
- Was the `CHECKING` account the only one in the list?
- Was it already selected when the `Select your account` view appeared?
- Can you please describe more precisely where you tap when it works and when does not work?
 Is it only on the checkmark, or the text, or all of the table view cell? 
- Does it behave differently when you run LinkKit in an actual iOS application as opposed to an Application Extension?

Of course a minimal running project that demonstrates the issue is much appreciated, yet a screen recording where the taps are visible would also be very helpful.

I'd also like to point out that [LinkKit version 1.1.0](https://github.com/plaid/link/releases/tag/ios%2F1.1.0) is not suitable for production :warning: use since the binary contains GCC and LLVM instrumentation code, which will be rejected during App Store submission or review. :information_source: Also [LinkKit version 1.1.3](https://github.com/plaid/link/releases/tag/ios%2F1.1.3) has been released, may I suggest you try that version and see whether the issue is resolved or can still be observed.

**Comment by hsmith825** [comment]
Hi AFH,
pod update Plaid which updated LinkKit to version 1.1.3 solved the problem.

Thanks for the quick response!!!
Howard

**Comment by afh** [comment]
@hsmith825 Glad to hear that 🙂👍
