### ISSUE TITLE
Don't silently fail and not provide feedback to the user when their device blocks pop-ups on mobile browsers (link V2)

### ISSUE THREAD

**Issue by EpiphanyMachine** [plaid/link#229]
#### Enhancement Request: 
- Don't **silently** fail and not provide feedback to the user when their device blocks pop-ups on mobile browsers

#### Solution Ideas:
- inform the user a pop-up blocker has blocked the page 
  - even better: show them how to allow pop-ups
- revert to V1 functionality and use an Iframe
- anything that doesn't silently fail to give the user any feedback

#### Steps to reproduce
- use link V2
- use a mobile browser (opens in new-tab vs iframe)
- visit site and trigger the login prompt
- block pop-ups for the site (or don't click allow)
- subsequent visits will not prompt for the pop-up being blocked and there is no feedback to the user why the login form did not appear

#### Background / More Info:

As noted in https://github.com/plaid/link/issues/124 Link V2 opens a new tab on mobile.

This has caused issues for some of us, but there is no supported workaround to revert to V1 functionality.  There is an unsupported workaround by forcing the `forceIframe` option.  https://github.com/plaid/link/issues/159

Some of mobile clients our users use block this new pop-up (probably because the user clicks the `x` vs `allow` when prompted.  See an example on the iPhone below:
![image](https://user-images.githubusercontent.com/4156958/35750451-e1db12b2-0809-11e8-833e-b2d6487ba12f.png)

**Comment by pbernasconi** [comment]
@EpiphanyMachine Thanks for raising this issue and the detailed investigation!

I agree we can improve the developer experience when integrating with Link for the mobile web. I've passed on your recommendations, and we're going to look into solutions for indicating when the Link new-tab on mobile is *not* opened. We have a few ideas that will address your concerns, so stay tuned for an update here in the next few weeks.

With regards to reverting to the V1 iFrame approach for mobile, we're also currently looking into that as a potential replacement of the mobile new-tab integration. The initial motivation for moving to a new tab was due to the fact that iFrames on mobile can be incredibly inconsistent and buggy depending on the mobile device, however we've made some great improvements to the `forceIframe` flag recently and believe we can offer the same experience in the same parent window. I can't give an expected date for an update here just yet, but will try to keep this thread up to date.

**Comment by pbernasconi** [comment]
@EpiphanyMachine – thanks for your patience on this issue in Link Web.

We recently pushed a change to Link on the Web, to default to the `forceIframe` experience for all users on mobile. What this means: Link no longer opens into a new tab - thereby eliminating the case where Link is blocked by pop-up logic on mobile.

Closing this issue as resolved now!
