### ISSUE TITLE
Please make it possible to support Subresource Integrity hashes for Plaid Link scripts

### ISSUE THREAD

**Issue by felixc** [plaid/link#231]
[Subresource Integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) (SRI) is a security feature whereby `<script>` tags can include a hash of the script they're loading, allowing browsers to verify that the script they fetch hasn't been tampered with and matches what the site publisher expects.

For a web product like Plaid Link that deals with extremely sensitive data, this is naturally a desirable property — if an attacker could compromise Plaid's script delivery, every customer would be affected and all their customers' data exposed, without the attacker having to compromise each site individually.

While in theory customers can to some extent add their own support for SRI in their own pages, there are a few things Plaid could do to make it easier and to give it an "official blessing".

Specifically, the current Plaid Link documentation suggests linking to script version `/v2/stable/` (https://plaid.com/docs/api/#integrating-with-link). This means the exact version of the script being served may change over time, meaning customers cannot add SRI without breaking the page whenever Plaid pushes an update.

If specific versions were published and their version numbers/release IDs/other stable identifiers included in the URL, customers could link to a specific, immutable, version of Plaid Link, and set an SRI hash for that version. There could still be a `/stable/` URL for users who don't want this feature, but specific versions would need to be prominently published and new releases prominently announced so that customers could update their embedded versions. Ideally, Plaid would publish the appropriate SRI hash along with the release, to make it even easier to update.

Downsides of course include the fact that some users of Link may never get around to updating their embedded version, or may do so very slowly. I don't have a good answer to how to avoid that problem, other than gently prodding those users to either ditch SRI and stick to the `/stable/` version, or reminding them to upgrade. The benefit to users who do stay up to date, however, would be a greatly enhanced security model and a lot of peace of mind.

**Comment by pbernasconi** [comment]
Hey @felixc – thanks for a great write up and detailed request, we really appreciate the thoroughness of your question. A few other Plaid customers have requested for SRI and we've spent some time looking into it.

After discussing SRI with the Link team and with our security team, we came to the conclusion that, while it's a great new protocol that's being adopted by modern browsers, it's not something that's possible for Link on the Web due to the fact that `link-initialize.js` is a dynamically changing script that we consistently push updates to.

SRI works by computing the hash of a `.js` file and hardcoding that into your `link-initialize.js` script tags, inside of your production HTML file.  The problem is that if we make any changes on our end, the hash changes, and requires coordination with our customers on updating to the latest version.  It's not something we can realistically do as it would slow us down a lot and would mean that we'd have to spend a ton of resources coordinating upgrades instead of building an awesome product. Coordinating these releases and ensuring that everyone is using the latest version would also introduce a lot of complexity for supporting backwards changes for those customers that lag several versions or weeks behind.

There is a proposal out there for using signatures for SRI instead of just hashes, which we believe solves this issue but still affords the benefits of SRI (read more about [Signature-based Resource Loading Restrictions](https://github.com/mikewest/signature-based-sri) here: https://github.com/mikewest/signature-based-sri).

When/if that becomes a reality, it's something we would likely support, however our answer for now is unfortunately that we cannot currently support SRI for Link on the Web.
