### ISSUE TITLE
Strange change in the buttons' color.

### ISSUE THREAD

**Issue by SergeiKu** [plaid/link#233]
| Name              | Value              |
| ----------------- | ------------------ |
| Link `apiVersion` |                   |
| Link `env`        |              sandbox      |
| LinkKit version   |      1.1.5              |
| iOS version       |     iOS 11.2.5               |
| iOS device        |      iPhone 6s              |

### A detailed description of the steps to reproduce the issue
Those buttons are hardly distinguishable the same as the "continue" button on the final screen. The "Submit" button becomes grey when there are some values in the both fields. I experienced this issue when integrated Plaid pod into the app. The issue doesn't exist in the demo app. 
Could you suggest a way to fix it, please? 
 
![img_0917](https://user-images.githubusercontent.com/25579299/36314885-3a42f58a-1347-11e8-95c4-5aca081483c9.jpg)
![img_0916](https://user-images.githubusercontent.com/25579299/36314888-3a613d10-1347-11e8-8ae0-65fb10c968f5.jpg)
![image uploaded from ios](https://user-images.githubusercontent.com/25579299/36317327-d9dd47ca-134d-11e8-8188-006eccaeba79.png)

**Comment by afh** [comment]
Hi @SergeiKu,

thank you for reaching out.

We have seen similar issues before when [`UIAppearance`](https://developer.apple.com/documentation/uikit/uiappearance) is being applied rather "broadly", e.g.

```
UIToolbar.appearance().barTintColor = customColor;
```

We recommend reviewing how `UIAppearance` is being used in your application and using [`appearance(whenContainedInInstancesOf:)`](https://developer.apple.com/documentation/uikit/uiappearance/1615013-appearance) to be more specific of where appearance should be altered.

We'll review what we can do to ensure that the design of LinkKit stays usable regardless of how `UIAppearance` is being used in host applications.

**Comment by SergeiKu** [comment]
Hi @afh  Thank you for your reply. Yes, you are right! At first I tried out `appearance(whenContainedInInstancesOf:PLKPlaidLinkViewController)` but that approach doesn't work as PLKPlaidLinkViewController present some other controllers during the workflow. Now I am looking another way to fix that issue. Thanks again!

**Comment by afh** [comment]
Thank you, @SergeiKu, for verifying.

Your application should **not** try to change the appearance of LinkKit's UI. If an application does not use `UIAppearance` or is more specific about it LinkKit's UI and colors will provide enough contrast to be usable.

What I meant to say previously is that your application is probably using `UIAppearance` too broadly, and that use affects LinkKit's UI.
Instead of trying to fix the colors for LinkKit, your application should set the appearance specific to your application's UI classes where appearance should change, e.g. `appearance(whenContainedInInstancesOf:YourAppViewController)`

Calling `appearanceWhenContainedInInstancesOfClasses:[PLKPlaidLinkViewController]` is something that LinkKit could and potentially should do to prevent applications from changing the appearance of its UI. We'll look into it for a future release.

**Comment by SergeiKu** [comment]
@afh Thank you again! Now I see the right way to fix the issue.

**Comment by afh** [comment]
Glad to hear that @SergeiKu 🙂 Looking forward to seeing LinkKit in your application.
