### ISSUE TITLE
Question about android web view demo

### ISSUE THREAD

**Issue by yuanliu666** [plaid/link#243]
| Link `env`       |   sandbox    |
| Browser          |   Android web view    |
| Operating system |   Android    |

### A detailed description of the steps to reproduce the issue
* Download and setup android web view demo;
* Add public key and log for `action`, namely current Uri host;
* Run app and log in a bank with sandbox credential;
* Check log info.

### What you expected to see?
As the code indicates when user successfully linked, the `action` should be `connected`.

### What you saw instead?
`action` = `event`

### A screenshot that shows the state of the UI (if applicable)
N/A

I am not sure if this is due to sandbox env (namely will not happen in dev/PRD env) or I misunderstand anything? Thanks!

**Comment by pbernasconi** [comment]
Thanks for opening this issue @yuanliu666 

Can you provide us with some example code of your integration. We unit test and integrate test our android webview integration, so I wouldn't expect to see this error.

**Comment by yuanliu666** [comment]
I have tried the web demo version of plaid link (https://demo.plaid.com/) and it looks like this after logged in:
![image](https://user-images.githubusercontent.com/13328332/39206809-02644572-47c4-11e8-9cd3-78673095722e.png)
They look different. Any idea why? Thanks.

**Comment by yuanliu666** [comment]
@pbernasconi OK I searched a little bit and read some docs. It's true that sandbox env matters because `connected` callback is after clicking the continue button. Still I have some questions:
1. From doc, it says `The selectAccount parameter controls whether or not your Link integration uses the Select Account view.` But from my practice, it decides whether the account info is returned. Could you please clarify?
2. `auth` and `transactions` both can be done in other platforms, so I guess there is a way for webview as well? Like `put("product", "transactions,auth")` instead when init `linkInitializeOptions`? Could you please let me know if that is correct?
3. When I tried `auth` for my citi bank account, it says `Account not currently supported`. Any idea why?

Thanks!

**Comment by pbernasconi** [comment]
Hey @yuanliu666 - Please excuse us for the late reply, but I think we've figure out why your receiving the wrong event. It turns out that a lot of the examples posted by other developers in the public Github issues have been setting the webview keyname (which is very important to get the right callbacks/messages in Link), as `isWebView` rather than `isWebview`.

Link is strict in interpreting the keys and configuration supplied during initialization, and while Link would still open correctly, we use the `isWebview` identified to determine what type of communication would be returned onSuccess / onExit. This is likely why you were not seeing thee `connected` event, even though our integration testing was confirming that it did exist.

I've gone and update the misspellings throughout the GitHub issues, and hope this fix works for you!

Please let us know if this does not work - and we'll dive deeper!

**Comment by pbernasconi** [comment]
@yuanliu666 I'm gonna close this out - since I believe the fix I mentioned above should address your issues!
