### ISSUE TITLE
App crashes when user tries to enter confirmation code sent to phonenumber

### ISSUE THREAD

**Issue by mariaschmiterlow** [plaid/link#252]
Hi,
We have one frequent crash in the iOS app connected to when user tries to enter a confirmation code sent to their phone (when connecting a bank). See stacktrace below.
We haven't been able to reproduce it, neither do we know if it only affects user that tries to enter a confirmation code or generally users confirming the connection with any other type of MFA question.
Have we configured LinkKit wrongly or is the problem on your side?

Link `apiVersion` (Where do I find this?)                 
Link `env` Transactions (in production)                     
LinkKit version 1.1.9                      
iOS version 97% on iOS 11, 2% on iOS 10 and 1% on iOS 12. But that is the general distribution for our app. So no iOS version specifically.                         
iOS device All iPhone device supporting the above iOS versions                    

![screen shot 2018-07-18 at 13 55 07](https://user-images.githubusercontent.com/15416618/42888177-f3a2082c-8aa7-11e8-9b92-c962bafc0231.png)

**Comment by afh** [comment]
Hello @mariaschmiterlow, thank you for reporting this.

The problem seems to be within LinkKit and I kindly request that you file an issue through [https://dashboard.plaid.com](https://dashboard.plaid.com/support/new/product-and-development/developer-lifecycle/link), mention this public GitHub issue, and kindly request that the created issue be directly passed on to the LinkKit developers.

The Link `apiVersion` can be set when configuring LinkKit, yet only in exceptionally rare cases should existing customers configure LinkKit to use Plaid's legacy API. You asking where to find this, indicates that you are and should be using the current default version of Plaid's API, i.e. `APIv2`.

**Comment by brutalkeso** [comment]
Hi @afh, @mariaschmiterlow is on vacation for the next couple of weeks. Could you relay this to the LinkKit developers? No one currently on-site has access to the dashboard.

**Comment by afh** [comment]
@brutalkeso Being one of the LinkKit developers I can say that we're already working on a fix. Yet we'd like to know more about the issue and need information from you for that, which must only be shared through private and secure channels, hence the request to open a support ticket through [https://dashboard.plaid.com](
https://dashboard.plaid.com/support/new/product-and-development/developer-lifecycle/link).

**Comment by afh** [comment]
Hello @mariaschmiterlow and @brutalkeso, wanted to let you know that the next release of LinkKit planned for mid August will contain a fix for this issue.

**Comment by mariaschmiterlow** [comment]
Hi @afh 
Sorry for the silence!
Thanks for getting back to us and thanks for fixing the issue to the next release!
Should I still create an issue through your dashboard tool?

**Comment by ravron** [comment]
Hi @mariaschmiterlow, I'd like to let you know that [LinkKit version 1.1.11][1] was released and addresses this crash. Please give it a try. Thanks again for your thorough report!

[1]: https://github.com/plaid/link/releases/tag/ios%2F1.1.11
