### ISSUE TITLE
[iOS] Close button on Plaid intro screen does not work

### ISSUE THREAD

**Issue by idris** [plaid/link#254]
| Name              | Value              |
| ----------------- | ------------------ |
| Link `apiVersion` | v2 |
| Link `env`        | production                   |
| LinkKit version   | 1.1.10                   |
| iOS version       | 11.4                   |
| iOS device        | iPhone X                   |

### A detailed description of the steps to reproduce the issue

* Open Plaid Link
* You will see the "This App uses Plaid to link your bank" intro screen
* Click the "X" in the top right to close Plaid Link.

### What you expected to see?
Expect Plaid Link to close.

### What you saw instead?
Nothing happens (actually, the status bar changes color.. but that's about it)

**Comment by afh** [comment]
Hello @idris thank you for reaching out and reporting this issue.

I'm unable to reproduce the described misbehaviour with the `Link-Demo` applications. Can you provide additional info on how you integrate LinkKit that may shed some light on the underlying cause.

Tapping the ✖️-button on the top right should call the `linkViewController:didExitWithError:metadata` delegate method of the `id<PLKPlaidLinkViewDelegate>` object and it is the delegate's responsibility to dismiss the presented `PLKPlaidLinkViewController`.

Does your delegate object receive the `didExitWithError:` message?

**Comment by Sethmr** [comment]
I am receiving this error as well. didExitWithError is getting hit, but for some reason it doesn't dismiss during the functions block. I provide the code below. If I set a breakpoint on the dismiss line, it gets hit. It I set one in the completion block, it will get hit once per time I hit the X on the first page plus one more for wherever else I hit the X. The problem only exists on the very first page. I would guess some kind of retaining cycle is responsible for this behavior, but your guess is surely far better than mine. I don't remember this problem existing in prior versions, so it is probably only a bug in 1.1.10.

At my company, we have tested this on multiple devices and not found any device where the bug does not occur. Since it is only on the intro page, it is an easy bug to miss.
```
    func linkViewController(_ linkViewController: PLKPlaidLinkViewController, didExitWithError error: Error?, metadata: [String: Any]?) {
        linkViewController.dismiss(animated: true) { [weak self] in
            if let error = error {
                self?.handleError(error, metadata: metadata)
            } else {
                self?.handleExitWithMetadata(metadata)
            }
        }
    }
```

**Comment by afh** [comment]
@Sethmr Thank you for your input.

In the code example you provided `dismiss` should not be called on `linkViewController` but rather on the view controller that presented the `PLKPlaidLinkViewController`, for a working example see [LinkDemo-Swift4/ViewController.swift:134](https://github.com/plaid/link/blob/master/ios/LinkDemo-Swift4/LinkDemo-Swift4/ViewController.swift#L134).

**Comment by afh** [comment]
@idris Is it possible that you are running into the same issue as @Sethmr?

**Comment by Sethmr** [comment]
I believe that this was pulled verbatim from one of your previous tutorials. I will let you know if this solves the issue tomorrow.

**Comment by afh** [comment]
Thank you for the quick response, @Sethmr. 

The code examples in the Link iOS documentation are generated from the actual source code of the different Link Demo applications, since that code hasn't changed in a while I'm a bit surprised to hear that. Then again, mistakes do happen.

If the code you used and posted in your previous message was indeed pulled verbatim from one of our previous tutorials please do let us know which one so we can correct it 🙂

**Comment by Sethmr** [comment]
I was able to get it working fine once I used the presenting ViewController to dismiss it. I found the old demo i used and I couldn't find an example of the code I claimed to copy and paste, so perhaps I was mistaken. I have grown a lot since last year :) Anyhow, I would assume the other guy is facing the same issue. Thanks for your help!

**Comment by afh** [comment]
@Sethmr Anytime! I'm happy to hear that you were able to resolve the issue you were having.

**Comment by idris** [comment]
@afh I haven't had time to check if `didExitWithError` is being called yet, but I should note that this ONLY happens on the first "This App uses Plaid to link your bank" screen.  If I hit "Continue" on that screen, then hit the X, it closes just fine.

**Comment by Sethmr** [comment]
@idris I can confirm the exact same behavior before fixing the bug with the solution they described. Surely something similar is going on with your side of things.

**Comment by idris** [comment]
@Sethmr You're saying I need to add something like `linkViewController.dismiss(animated: false)` to my `handleExit` callback?  If so, that seems like it's a bug in the Plaid Link library, especially since all of the other screens work properly when tapping "X" to close.

Also, I don't see any of the demo apps in this repo calling `dismiss` on the `linkViewController` manually.

**Comment by Sethmr** [comment]
I'm saying if the class that you have conforming to `PLKPlaidLinkViewDelegate` is a view controller you should do a `self.dismiss(animated: false)`, otherwise you should pass a weak reference to that view controller in and call `vcReference?.dismiss(animated: false).` `linkViewController.dismiss(animated: false)` is exactly what was causing the bug on my side.

**Comment by afh** [comment]
@idris Thanks for emphasizing that it only happens on the very first screen, yet I'm still unable to reproduce the issue. Can you reproduce it with any of the LinkDemo applications?

**Comment by afh** [comment]
Furthermore I'd like to propose to call `linkViewController.presentingViewController?.dismiss(animated: false)` instead of ~~`linkViewController.dismiss(animated: false)`~~ in case the `PLKPlaidLinkViewDelegate` object does not have a reference to the original view controller instance presenting the `PLKPlaidLinkViewController`.

**Comment by afh** [comment]
@idris The latest release of LinkKit ([v1.1.12](https://github.com/plaid/link/releases/tag/ios%2F1.1.12)) addresses this issue and allows `dismiss` to be called on the passed `linkViewController` parameter.
