### ISSUE TITLE
Correct Prepare for Distribution instructions and how to make distribution / simulator coexist

### ISSUE THREAD

**Issue by xuefanzhang** [plaid/link#283]
*Please do not include your API `secret` or `public_key` in any issue.*
---
### A detailed description of the steps to reproduce the issue

* Integrate LinkKit.framework via **Carthage**. 
* Followed the manual steps, including setting Set up `FRAMEWORK_SEARCH_PATHS = $(PROJECT_DIR)/Carthage/Build/iOS`
* Verified that plaid integration works well when tested using simulator
* Try to Archive + distribute without following the prepare for distribution step, get Invalid Signature error on prepare_for_distribution.sh. Saw that prepare_for_distribution.sh is still in LinkKit.framework
* Add Prepare for Distribution run script.
* Product -> Archive. Silently fails. Looks like prepare_for_distribution.sh is removed, but no build uploaded to App Store Connect.
* If I try to product -> archive again, it fails to find the prepare_for_distribution.sh file (makes sense as it was removed in the last step.) If I remove the Prepare for Distribution step from the build phase, then archive, I can now successfully upload to the App Store Connect. However, building in simulator fails (I think this is expected as the format that supports the simulation is removed?)

### What you expected to see?
A way for simulator and app distribution to work simultaneously. I'm guessing surely I don't need to re-obtain LinkKit.framework via Carthage and relink library after every archive? What am I doing wrong?

<details><summary>Screenshots that show the state of the UI (if applicable)</summary>

1.

![screen shot 2018-10-31 at 7 12 53 pm](https://user-images.githubusercontent.com/2301245/47828607-07e71e80-dd41-11e8-91db-f474ae9cf355.png)

2.

![screen shot 2018-10-31 at 7 41 40 pm](https://user-images.githubusercontent.com/2301245/47829520-2c44fa00-dd45-11e8-8ab1-8141248e911c.png)

</details>

When submitting an issue for [**Plaid Link iOS**](https://github.com/plaid/link/tree/master/ios) please include the following information:

| Name            | Value |
|-----------------|-------|
| Link `env`      | sandbox|
| LinkKit version |1.1.13 |
| Xcode version     | 10.0 |
| iOS device      | Generic iOS device|

#### List of used 3rd party libraries (e.g. CocoaPods):

* Carthage

Please let me know if there is anything else you need. Really appreciate your help!!

**Comment by xuefanzhang** [comment]
I looked into the folder where it's trying to locate prepare_for_distribution.sh, and there is indeed no prepare_for_distribution.sh there.
![screen shot 2018-11-01 at 10 40 57 am](https://user-images.githubusercontent.com/2301245/47868935-c9924380-ddc2-11e8-9506-17bfe24d867b.png)

**Comment by xuefanzhang** [comment]
ok! I googled a bunch online and it seems that the prepare_for_distribution file is no longer needed? At least for integrating via Cocoapods. Is that the same for Carthage? If so, would be great to update the instructions :) It's kind of weird because I was getting the prepare_for_distribution error yesterday. Is this a recent change? I suspect in the previous version prepare_for_distribution was included?
![screen shot 2018-10-31 at 11 53 37 am](https://user-images.githubusercontent.com/2301245/47871410-40cad600-ddc9-11e8-9706-3d4a0be33740.png)


I removed

**Comment by afh** [comment]
Hi @xuefanzhang,

thank you for using Plaid Link for iOS. The [documentation](https://plaid.com/docs/link/ios/#add-run-script) will be updated to describe the specifics when integrating with Carthage better.

When integrating Plaid Link for iOS with Carthage the script is contained within the binary framework:
```
% carthage update
*** Fetching link
*** Checking out link at "ios/1.1.13"
*** xcodebuild output can be found in /var/folders/st/7n10np2s23l0mhcl3ghpt8_978ym42/T/carthage-xcodebuild.GBCrRA.log
*** Downloading link.framework binary at "LinkKit 1.1.13"

% openssl dgst -sha512 Carthage/Build/iOS/LinkKit.framework/prepare_for_distribution.sh
SHA512(Carthage/Build/iOS/LinkKit.framework/prepare_for_distribution.sh)= 445330b3e8216f0d8bb576defa9dab675864ee0e5e8a2c62ebad3e2e59baf14ff741bf7738200c907e330ee190462f81318994338a73cd3859e7ae31a9a304ad
```

The custom Run Script Phase is necessary, since otherwise LinkKit.framework contains resources (symbols for running on the iOS simulator and the `prepare_for_distribution.sh` script) which must not be submitted to the App Store.

Please ensure that the your custom **Run Script Phase** (Prepare for Distribution) runs *after* the  **Embed Frameworks** build phase, and change the Run Script to the following (notice that `LINK_ROOT` defaults to `Carthage/Build/iOS` if unset:

```
LINK_ROOT=${PODS_ROOT:+$PODS_ROOT/Plaid/ios}
cp "${LINK_ROOT:-Carthage/Build/iOS}"/LinkKit.framework/prepare_for_distribution.sh "${CODESIGNING_FOLDER_PATH}"/Frameworks/LinkKit.framework/prepare_for_distribution.sh
"${CODESIGNING_FOLDER_PATH}"/Frameworks/LinkKit.framework/prepare_for_distribution.sh
```

Let me know if this works for you.

**Comment by xuefanzhang** [comment]
Hi @afh - I removed then relinked LinkKit, added the Prepare for Distribution run script, and it worked out great! Do you have a hunch for why it was causing trouble before? I think the run script I had before should do the same thing as the one you posted, and it was after the embed frameworks build phase. For it to run after the embed frameworks build phase, it just needs to be positioned after it in the Build Phases, correct?
![screen shot 2018-11-05 at 10 58 08 am](https://user-images.githubusercontent.com/2301245/48020024-bdbbbf80-e0e9-11e8-868d-f1bbb84de143.png)

Also, any hints on why it now works both with deploy and simulator? My understanding is that prepare_for_distribution.sh strips away formats e.g. x86_64 and i386 that are used by the simulator. 

**Any info/explanation would be greatly appreciated :) After being stuck on it for some time I'm pretty curious for what's happening under the hood, and also just want to make sure it's doing what it's supposed to be doing so it doesn't end up getting rejected by App Store down the line.** THANK YOU!!!

**Comment by afh** [comment]
Hi @xuefanzhang :wave:

first of all I'm happy to hear that things are now working for you! :tada:

To answer your questions:

* Yes, I do know  why it was causing trouble. Because it was *not* the same script.
  The script recommended on [plaid.com/docs/link/ios/](http://plaid.com/docs/link/ios/) does not handle Carthage well, it defaults the `LINK_ROOT` variable to the Xcode build variable `$PROJECT_DIR` assuming that is where the LinkKit.framework can be found. In the script that I recommended to you `LINK_ROOT` defaults to the Carthage build directory `Carthage/Build/iOS`, i.e.
`cp "${LINK_ROOT:-$PROJECT_DIR}"/LinkKit.framework/prepare_for_distribution.sh …`
vs.
`cp "${LINK_ROOT:-Carthage/Build/iOS}"/LinkKit.framework/prepare_for_distribution.sh …`
Changes to improve support for all integrations are in the works.

* Correct, positioning the custom **Prepare for Distribution** Run Script phase *after* the **Embed Frameworks** Build Phase makes the former run after latter. 👍 

* It now works with both the device and simulator builds, because now it works as intended 😄
If you look closely at the [prepare_for_distribution.sh](https://github.com/plaid/link/blob/master/ios/LinkKit.framework/prepare_for_distribution.sh#L16) script it uses the `${ARCHS}` Xcode build variable to determine which architectures are currently being built and then removes all others from the framework that is being embedded into the application.
So for simulator builds all ARM architectures are removed and for iOS device builds all *86 architectures are removed.
If you want to check which architectures are contained in LinkKit to the following:
```
% lipo -info Carthage/Build/iOS/LinkKit.framework/LinkKit
Architectures in the fat file: Carthage/Build/iOS/LinkKit.framework/LinkKit are: i386 x86_64 armv7 arm64 
```
then for fun run the same command on the LinkKit.framework embedded into a build of your application:
```
% lipo -info $HOME/Library/Developer/Xcode/DerivedData/LinkDemo-ObjC-elpcckmkinlikdamhnfdgaoqwwnd/Build/Products/Debug-iphonesimulator/LinkDemo-ObjC.app/Frameworks/LinkKit.framework
Architectures in the fat file: LinkKit are: x86_64
```

**Comment by xuefanzhang** [comment]
thank you so much @afh !! That explains everything :D Really appreciate your help. Now just a friendly reminder to update the doc for Carthage when you guys have some time :).

Thank you again!
