### ISSUE TITLE
Don't show technical error messages to end users!

### ISSUE THREAD

**Issue by idris** [plaid/link#285]
### A detailed description of the steps to reproduce the issue

* Rotate API keys
* Open Plaid Link with an old (disabled) API key

In our case, we rotated keys and also had our API v1 keys disabled so nobody could use it.

### What you expected to see?
Some generic user-friendly error message.

### What you saw instead?
A very non-user-friendly error message, with HTML and a link to Plaid support in it.  You should never reference "Plaid Client ID" or this kind of stuff to end users.
See screenshot below.

<details><summary>Screenshots that show the state of the UI (if applicable)</summary>

![plaid-client-id-error](https://user-images.githubusercontent.com/13989/48512864-78556b80-e828-11e8-88f5-954085c2459c.png)

</details>

---

| Name            | Value |
|-----------------|-------|
| Link `env`      |   production   |
| LinkKit version |   1.1.9? Not 100% sure  |
| iOS version     |   12.0.1   |
| iOS device      |    iPhone 7 Plus   |

**Comment by pbernasconi** [comment]
Hey @idris – sorry for the delayed response, I hope someone from our support team was able to answer you issue internally.

Unfortunately there is no easy fix for this:
- Because your users are seeing this in the Link iOS SDK, you would have to release a new version of your app to get a fix to this messaging
- Your users would therefore have to upgrade their Truebill iOS app to get this fix – where they would actually no longer be using the legacy Plaid API, rendering this fix moot
- As such, there is no action that we can immediately take to resolve this issue unfortunately

Do you know how many users are affected by this messaging?

Can I suggest that you prompt your users to upgrade to your new iOS release somehow in the Truebill app?
