### ISSUE TITLE
Issues with iOS account link and balance access

### ISSUE THREAD

**Issue by Demolisty24** [plaid/link#286]
*Please do not include your API `secret` or `public_key` in any issue.*
---
### A detailed description of the steps to reproduce the issue

When I permitted the user only the one of the account to be selected which then generated the token for the item. However once I exchanged the token for a private_token and proceed to get the balances of the item, I get the balance of all of the account that is associated with the institution not just the selected one. 

### What you expected to see?

Item access only to the selected account in the interface

### What you saw instead?

All information of the accounts in the same institution with the selected account

When submitting an issue for Link on the web or within a Webview, please include the following information:

When submitting an issue for [**Plaid Link iOS**](https://github.com/plaid/link/tree/master/ios) please include the following information:

| Name            | Value |
|-----------------|-------|
| Link `env`      |    .develoment   |
| LinkKit version |   current   |
| iOS version     |    12.1    |
| iOS device      |   XR    |

#### List of used 3rd party libraries (e.g. CocoaPods):

* [Plaid](https://cocoapods.org/pods/Plaid)
* [Firebase]
*

**Comment by afh** [comment]
Thank you for reporting @Demolisty24.
Looking into it.

**Comment by afh** [comment]
Hi @Demolisty24,

**selectAccount** acts as a basic built-in filter by providing the selected `account_id` in the metadata of the `linkViewController:didSucceedWithPublicToken:metadata:` delegate method.

Regardless of that Plaid still pulls down all available accounts and their data. In order to retrieve specific account information you need to specify the `account_id` in the `account_ids` array of the `options` field in the request to `/accounts/balance/get` (see [endpoint documentation](https://plaid.com/docs/#balance)).
