### ISSUE TITLE
ERR_UNKNOWN_URL_SCHEME on Android

### ISSUE THREAD

**Issue by kstanislav** [plaid/link#288]
---
### A detailed description of the steps to reproduce the issue

* Open Plaid Link webview with setup like here: https://github.com/plaid/link/blob/master/webviews/examples/android/app/src/main/java/plaid/samplewebviewapp/MainActivity.java
* Start activity

### What you expected to see?
Welcome plaid screen with "Continue" button.

### What you saw instead?

"Web page not available"

The webpage at plaidlink://event?error_code&error_message&error_type&....

could not be loaded because:
net::ERR_UNKNOWN_URL_SCHEME

<details><summary>Screenshots that show the state of the UI </summary>

![image from android](https://user-images.githubusercontent.com/13114540/49447271-c08bfc00-f7de-11e8-8005-62aa008feef3.jpg)

</details>

Problem reproducing on Samsung Galaxy A7, Motorola G and some other devices..
Testing on LG G6, LG G3 Stylus, LG G5, LG Google Nexus.. everything OK.

---

When submitting an issue for Link on the web or within a Webview, please include the following information:

|       Name       | Value |
|------------------|-------|
| Link `env`       |    sandbox\production   |
| Browser          |   Android WebView    |
| Operating system |   Android 6.0.1, Android 5.1   |

---

**Comment by ravron** [comment]
Hello @kstanislav! Link uses special `plaidlink://` redirects to communicate analytics from webviews back to the host app, which are [documented here under "Communication between Link and your app."](https://plaid.com/docs/#webview-integration). To properly integrate with Link, your activity must override loading of such URLs, as is [done in the example](https://github.com/plaid/link/blob/master/webviews/examples/android/app/src/main/java/plaid/samplewebviewapp/MainActivity.java#L54-L109). If you don't override the redirects, your webview will try to actually load a `plaidlink://` URL, which will of course fail, since that's not a valid scheme. 

Give that a shot and let me know here if that helps. Thanks!

**Comment by kstanislav** [comment]
@ravron Hah!! How can you imagine, but with deprecated `shouldOverrideUrlLoading(view: WebView, url: String)` method it finally works.
Seems like some OS specific behavior going there.. webView doesn't invoke actual method but invoke deprecated one, but nor Android Studio nor Lint, ktLint, etc.. don't aware developers about. 

So now code looks like:

```
webViewPlaid.webViewClient = object : WebViewClient() {

            override fun shouldOverrideUrlLoading(view: WebView?, url: String?): Boolean {
                return view?.let { initializePlaid(it, Uri.parse(url ?: "")) } ?: false
            }

            override fun shouldOverrideUrlLoading(view: WebView, request: WebResourceRequest): Boolean {
                return initializePlaid(view, request.url)
            }
        }
```
Thank you @ravron again, you directed me right way.

**Comment by ravron** [comment]
I wish I had an explanation for why your prior code didn't work, but I'm glad to hear you're up and running @kstanislav!

**Comment by ergindogan** [comment]
This helped me too, thanks @ravron!

**Comment by nullptr2this** [comment]
This is a life saver.  Thanks @ravon and @kstanislav for digging into it.
