### ISSUE TITLE
Removing items for churned users

### ISSUE THREAD

**Issue by ghking** [plaid/link#324]
As users churn, what's the recommended way to remove `Item`s? For example, if a user uninstalls the app without first explicitly unlinking their accounts (where we wouldn't have the chance to call the `/item/remove` endpoint) there would be an orphaned `Item` which would still be eligible for billing forever, even though it's not being used anymore.

One option would be to store the access tokens off-device on the server, and keep track of the time they were last used. Then remove their associated `Item` if they haven't been used in X months. That could potentially lead to some UX issues though if a user returns to the app after that amount of time, so I'm wondering if there's a better way or a mechanism that handles this that I missed in the docs.

Hope that makes sense. Thank you!

**Comment by ravron** [comment]
Hi @ghking! There aren't actually any tricks or mechanisms beyond what you've already described — it's a tough problem. We (Plaid) don't attempt to guess when an item is no longer useful for our customers, because every use-case is different. What you've suggested makes sense: determine some threshold after which you think a user is unlikely to return. When it has elapsed, remove their items via the `/item/remove` endpoint, then delete or tombstone the tokens on your end. If the user ever does return, they'll have to re-link their accounts, but this shouldn't come as too much of a surprise to a user who's been inactive for a long period.

I have an important, related note. You say:

> One option would be to store the access tokens off-device on the server…

Regardless of how you deal with items associated with inactive users, it's crucial that you always store access tokens in a secure environment, and never on users' devices, where they could be compromised. Plaid access tokens are sensitive information, in that they can be used, in combination with your client ID and secret, to access users' financial data. That's why the token exchange process is mediated by your backend, not your mobile app or website.

If you have further questions, please don't hesitate to file a support ticket through our dashboard. Thanks!

**Comment by ghking** [comment]
Makes sense! Thanks for the quick and detailed answer. That really helps clear things up.

As for "off-device", I meant that as a given rather than as part of just that particular option, but thank you for clarifying as security is definitely very important for this kind of application. I probably could have made that wording more clear.

Thanks again @ravron!
