### ISSUE TITLE
"Other" options which falls back to account and routing number

### ISSUE THREAD

**Issue by jclay** [plaid/link#54]
The modal works perfectly if a user has one of the supported bank accounts, but there is no option for "Other" if you don't have one of the supported bank accounts. As a result, the user must know to exit the modal and use a fallback presented on the website.

**Comment by michaelckelly** [comment]
@jclay 

Thanks for the feedback - while Link does not offer this functionality at this time, you can use the [custom integration][1] to present your own 'select your bank' UI rather than Link's standard institution select UI. This allows you to present an alternative if the user does not bank with a Plaid-supported institution. Hope this helps!

[1]: https://github.com/plaid/link#step-2-custom-integration

**Comment by jclay** [comment]
Are any of the UI resources provided to create a custom integration such as supported institution logos and names?
