### ISSUE TITLE
Simple Implementation Error on Submit

### ISSUE THREAD

**Issue by marcstein** [plaid/link#80]
When testing the simple implementation on tartan, submit on the final widget screen raises the following error:

link-initialize.js:1 Uncaught TypeError: g.submit is not a functionq @ link-initialize.js:1(anonymous function) @ link-initialize.js:1

POST is never made to '/authenticate'

Thanks,

Marc

**Comment by michaelckelly** [comment]
@marcstein - Can you please provide more information about the browser / platform / etc? We'll be able to investigate faster with that information.

**Comment by marcstein** [comment]
Hi Michael,

Sorry about that! Platform is OSX 10.11.4 and the same error occurs on
Chrome, Safari, and Firefox.

It may well be that something is missing in my code. This is a really
simplistic test and the contents of my index file are:

<HTML>
<HEAD></HEAD>
<BODY>
<DIV><h2>Underwrite.io</h2></DIV>
<DIV id="widget">
<form id="widget" method="POST" action="/authenticate"></form>
</DIV>


</BODY>

<script
  src="https://cdn.plaid.com/link/stable/link-initialize.js"
  data-client-name="Underwrite.io"
  data-form-id="widget"
  data-key="test_key"
  data-product="auth"
  data-env="tartan">
</script>

</HTML>


Error is:

 link-initialize.js:1 Uncaught TypeError: g.submit is not a functionq @
link-initialize.js:1(anonymous function) @ link-initialize.js:1

Thanks,

Marc

**Comment by pbernasconi** [comment]
Hi @marcstein, thanks for raising your issue – the problem that you've encountered is likely because your `index.html` file has 2 `id` attributes with the same value of `widget`, which is invalid HTML and doesn't allow Link to initialize properly.

Instead only one `id` attribute should be available on the `form` element like so:
```html
<div>
<form id="widget" method="POST" action="/authenticate"></form>
</div>
```

It's also important that you include the `<script src="..."></script>` tag is **before** the closing body tag, and not after:

```html
</html>
<body>

<form id="..."></form>
<!-- script comes after the form element, and before the closing body tag -->
<script src="https://cdn.plaid.com/link/stable/link-initialize.js"></script>

</body>
</html> 
```

Please reach out again if you have any other issues!
