### ISSUE TITLE
Webhook returning institution type

### ISSUE THREAD

**Issue by mladenbolic** [plaid/link#82]
We experienced strange behaviour when using Plaid Link test environment.

After institution is linked, everything works ok if user closes the Plaid Link modal. The `onSuccess` callback is triggered, we exchange public token for access token and we save institution type/access token pair to the database.

But if user does not close the modal, the `onSuccess` doesn't get called and it's possible that webhook gets triggered before we get a chance to exchange the tokens. Retrieving transactions will still work in this case (access token is sent within webhook body), but we cannot save the access token to the database, since we do not know its institution type. And if user doesn't close the modal, exchange token action will never occur.

Is it possible to send the institution type as part of the webhook body?

This way we would have an easy flow saving the access token, even if user (for some reason) doesn't close the modal.

**Comment by ritec** [comment]
I ran into an issue related to this as well... it was causing a race condition in our application, because the webhooks occurs even before the user closes the modal as you say. When the webhook is triggered the object in our environment has not yet been created if the modal has not been closed and thus it's not possible to find the object the webhook belongs to. I coded around it but it's worth noting this type of scenario can happen.

**Comment by idris** [comment]
Yep, what @ritec is seeing has always been a big confusion point for us as well.

@mladenbolic the way we got around it is that in the webhook we hit Plaid's API to get the accounts (and `institution_type`), _then_ store it.

Of course it'd be nice if Plaid fixed this issue and got rid of the race condition.

**Comment by michaelckelly** [comment]
You should no longer receive webhooks for an Item before you exchange its `public_token` for an `access_token`(if you're using our legacy API, you may still experience this behavior).

[1]: https://plaid.com/docs/api
