### ISSUE TITLE
Getting institution public_token

### ISSUE THREAD

**Issue by mladenbolic** [plaid/link#86]
We have an issue with current Plaid API.

We used Plaid Link to link the institutions, and we saved only the access_token, which we used to retrieve the list of transactions. In order to use Plaid Link for updating user MFA, we need public_token info. 

Is there a way to retrieve the public_token by sending the API request containing client_id, secret, access_token?

**Comment by michaelckelly** [comment]
@mladenbolic - There is not an API endpoint that does this at this time. We're happy to share a list with you, though - just reach out to support@plaid.com with your client ID and we'll take it from there!

**Comment by idris** [comment]
Seems like there's an endpoint for this in API v2 now: https://plaid.com/docs/api/#creating-public-tokens

Will that work for access_tokens created with API v1?  If not, is there an analogous API v1 endpoint?  Due to the race condition mentioned in #58, we end up with a lot of items without publicTokens.
