### ISSUE TITLE
get Public_token from Mobile endpoint

### ISSUE THREAD

**Issue by raedonbd** [plaid/link#87]
We are trying to implement PLAID but we using the HTML drop in link to get public token  then use endpoint /exchange_token to get access_token , where as our mobile devices application can connect to plaid directly and get access_token, is there a way to get public_token from mobile through a plaid endpoint . Since we want to store the both the public token and access_token for a users bank account with plaid. 
any suggestions or code snippets  would be a great Help

**Comment by pbernasconi** [comment]
Hi @raedonbd – you shouldn't be making API requests to Plaid using your `client_id` and `secret`, as this poses a large security risk. Those two values are private and should only be used to make requests using a backend server. This is because iPhone and Android apps can be Jailbroken and read by anyone downloading your app.

Instead you should likely build a backend service to make API requests from your mobile application. Please check out some of the examples in the [examples folder](https://github.com/plaid/link/tree/master/examples) for a sample integration with our API
