### ISSUE TITLE
TypeError inside link-initialize.js

### ISSUE THREAD

**Issue by bencmbrook** [plaid/link#99]
```
[Error] TypeError: null is not an object (evaluating 'document.body.appendChild')
    (anonymous function) (link-initialize.js:2:1837)
    s (link-initialize.js:1:624)
    e (link-initialize.js:1:792)
    (anonymous function) (link-initialize.js:1:809)
    (anonymous function) (link-initialize.js:1:317)
    global code (link-initialize.js:1:322)
[Error] ReferenceError: Can't find variable: Plaid
    global code (yo.com (line 59))
```

which is:

```
57  <script src="https://cdn.plaid.com/link/stable/link-initialize.js"></script>
58  <script>
59    var linkHandler = Plaid.create({
...
```

The script and linkHandler (line 57 onwards) is sent from Express as a view to the `<head>` of each page in the app. When I put the same script in the body of a particular page (with Angular), **the first error goes away however the ReferenceError for the variable Plaid remains**.

Not sure where I've gone wrong to be getting an error like this. I'm using Angular and Node ([MEAN.js](http://meanjs.org))

**Comment by pbernasconi** [comment]
@bencmbrook thanks for raising this issue!

I believe you're seeing this issue because you're putting the `link-initialize.js` and handler script in the `<head>` of the html page. Link **must** be placed in the `<body>` of an html page in order for the modal to be appended properly. We are in the process of improving error message around the `link-initialize` script however, to provide more context about implementing Link correctly.

Please let us know if this solves your issue, otherwise would you please send more information about, and the Link team will continue to investigate the issue.
- Browser + version
- OS + OS version
